version: '3.9'

services:

  app:
    build:
      context: .
    image: &mysite mysite
    ports:
      - 8000:8000
    command: >
      sh -c ' python manage.py runserver 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/db
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
    ports:
      - 5432:5432

volumes:
  db-data: