version: '3.9'

services:

  app:
    build:
      context: .
    image: &mysite mysite
    ports:
      - 8000:8000
    volumes:
      - ./mysite:/mysite
    env_file:
      - .env
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

volumes:
  db-data: